language: generic
sudo: required

branches:
  only:
  - master
  - /^v\d+\.\d+\.\d+(-\S*)?$/

services:
  - docker

jobs:
  include:
    - stage: test
      script: make ci

    - stage: release
      if: branch = master OR tag IS present
      before_script:
        - git config --global user.email "support@travis-ci.org"
        - git config --global user.name "travisbot"
      script:
        - make generate
        - sudo chown -R travis:travis /home/travis/
        - LANG=go bash release/git.sh
        - LANG=web bash release/git.sh

notifications:
  email: false